// Banco de preguntas para las guías PDF de Profe Emi / AvíspateYa.
// Fuente: recopilación de preguntas oficiales estilo DEMRE (Puntaje Nacional),
// agrupadas por eje temático tal como las clasifica el propio documento fuente.
// Solo se incluyen enunciado + alternativas (sin solución) — son guías de
// práctica, no solucionarios.

export const NUMEROS = [
  { n: 1, enun: "¿Cuál es el valor de (1 − 1/4)(5·1/2 + 1)(1/3 + 1/5)?", alt: ["11/10", "13/10", "11/5", "13/5"] },
  { n: 2, enun: "Un ciclista va recorriendo una carretera en la cual cada 6 km hay postes con teléfonos de emergencia. El último poste que pasó se encuentra a 2,89 km. Al ciclista se le averió un neumático y debe caminar hasta el poste más cercano. ¿Cuál es la distancia, en metros, que caminará?", alt: ["3.110", "2.890", "890", "110"] },
  { n: 3, enun: "Una silla promedio de colegio tiene aproximadamente 1,8 kg de madera y 4,25 kg de acero. ¿Cuál es la expresión que representa la cantidad de kilogramos totales de masa de la silla?", alt: ["(18 + 425) : 10", "(180 + 425) : 10", "(180 + 425) : 100", "(18 + 425) : 1.000"] },
  { n: 4, enun: "El DEMRE publicó la distribución sugerida de 65 preguntas por eje: Números entre 12 y 24; Álgebra y funciones entre 9 y 18; Geometría entre 6 y 15; Probabilidad y estadística entre 6 y 15. ¿Cuál es el número mínimo de preguntas del eje Geometría que puede incluir la prueba?", alt: ["6", "8", "10", "12"] },
  { n: 5, enun: "Una familia posee tres perros como mascotas, cuyas masas están en una proporción de 7:2:5. Si sus masas suman en total 42 kg, ¿cuál es la masa del perro más ligero?", alt: ["3 kg", "6 kg", "9 kg", "12 kg"] },
  { n: 6, enun: "Cuatro amigos arriendan una cabaña por cinco noches y acuerdan dividir el precio por la cantidad de personas que se alojen cada noche. El arriendo es de P pesos por noche. Fernando solo se hospedará tres noches, y los tres amigos restantes todos los días. ¿Cuál expresión representa lo que deberá pagar Fernando?", alt: ["P/4", "P/5", "3P/4", "3P/5"] },
  { n: 7, enun: "¿Cuál de las siguientes expresiones representa el 10% del 25% de 60.000?", alt: ["35/100 · 60.000", "35/1.000 · 60.000", "25/100 · 60.000", "25/1.000 · 60.000"] },
  { n: 8, enun: "Si se sabe que el 85% de una comunidad está vacunada, ¿cuál de las siguientes afirmaciones es siempre FALSA?", alt: ["85 personas de la comunidad están vacunadas.", "15 de 100 personas de la comunidad no están vacunadas.", "Podemos conocer la cantidad vacunada multiplicando el total por 0,85.", "Si la comunidad tiene 1.000 personas, 850 están vacunadas."] },
  { n: 9, enun: "En la Patagonia chilena, un campesino notó que la población original de caballos aumentó en un 30% después de que las yeguas parieron. Si después la población es de 260, ¿cuál era la población original?", alt: ["60", "200", "230", "320"] },
  { n: 10, enun: "Una familia va a comer un jueves de septiembre a un restaurante con 40% de descuento en la carta (no aplica a la propina), consume D pesos en alimentos y deja una propina del 10% de D. ¿Cuál expresión representa el total que gastó la familia?", alt: ["D·0,6 + D·0,1", "D·0,4 + D·0,1", "(D + D·0,1)·0,4", "(D + D·0,1)·0,6"] },
  { n: 11, enun: "En una tienda hay una cantidad p de pelotas de tenis de mesa, solo blancas y naranjas, con b pelotas blancas. ¿Cuál expresión representa el porcentaje de pelotas naranjas?", alt: ["(pb)/100 %", "100/(pb) %", "(p−b)·100/p %", "(p−b)·p/100 %"] },
  { n: 12, enun: "Felipe tiene 5 evaluaciones con ponderaciones 5%, 25%, 15%, 25%, 30% y notas 6,3 / 5,5 / 7,0 / 6,7 / 4,9. ¿Cuál operación expresa cómo calcular su nota final?", alt: ["(6,3·0,05)+(5,5·0,25)+(7,0·0,15)+(6,7·0,25)+(4,9·0,30)", "(6,3·0,5)+(5,5·2,5)+(7,0·1,5)+(6,7·2,5)+(4,9·3,0)", "(6,3·5)+(5,5·25)+(7,0·15)+(6,7·25)+(4,9·30)", "(6,3·50)+(5,5·250)+(7,0·150)+(6,7·250)+(4,9·300)"] },
  { n: 13, enun: "7√32 − 2√50 es igual a", alt: ["40√2", "18√2", "20", "12"] },
  { n: 14, enun: "¿Por cuál de los siguientes números habrá que multiplicar √5 para obtener 5?", alt: ["√2", "√5", "5", "10"] },
  { n: 15, enun: "¿Cuál es el orden, de menor a mayor, de T=1/(5√3), P=1/9, Q=1/(6√2), M=1/(4√5)?", alt: ["P, M, T, Q", "M, T, Q, P", "P, Q, M, T", "Q, T, M, P"] },
  { n: 16, enun: "Si 3^n = 9 · 9 · 9, ¿cuál es el valor de n?", alt: ["3", "6", "9", "12"] },
  { n: 17, enun: "¿Cuál de las siguientes afirmaciones es siempre verdadera?", alt: ["Cualquier potencia de base racional y exponente cero es igual a uno.", "Una potencia con exponente negativo siempre es positiva.", "Toda potencia de base uno y exponente racional es igual a uno.", "Para (aⁿ)ᵐ se conserva la base y se suman los exponentes n y m."] },
  { n: 18, enun: "En una coreografía, los bailarines saltan: primero 2 m hacia adelante; luego la mitad del salto anterior hacia la derecha; luego la mitad del anterior hacia atrás. ¿Cuál expresión representa la cantidad de metros que se desplaza cada bailarín?", alt: ["2 + 4(1/2) + 6(1/2)²", "2 + 2(1/2) + 2(1/2)²", "2(1/2)³", "2(1/2)²"] },
  { n: 19, enun: "En un cultivo, cada bacteria se reproduce por bipartición cada 2 horas. Si inicialmente había una población de 4¹⁰ bacterias, ¿en cuántas horas habrá 64¹⁰ bacterias?", alt: ["80", "60", "16", "8"] },
];

export const ALGEBRA = [
  { n: 20, enun: "¿Cuál opción debe ser equivalente a P en P − 18y⁴ para que se factorice como 2(2x³+3y²)(2x³−3y²)?", alt: ["4x³", "4x⁶", "8x³", "8x⁶"] },
  { n: 21, enun: "Si a + b = 16 y a² − b² = 48, entonces a − b =", alt: ["3", "32", "4", "36"] },
  { n: 22, enun: "Carolina desea encontrar la solución del producto notable (2/5·y − 1/4·w)². ¿Cuál es el resultado?", alt: ["w²/16 − wy/5 + 4y²/25", "w²/16 + wy/5 + 4y²/25", "w²/16 − wy/5 − 4y²/25", "w²/16 + wy/5 − 4y²/25"] },
  { n: 23, enun: "Constanza recaudó $(3p+5)/3 y Alejandra $3(q−2) para sus vacaciones. ¿Cuál expresión representa el dinero total ahorrado entre las dos?", alt: ["p + 3q + 13/3", "p + 3q − 13/3", "p + 3q + 1/3", "p + 3q − 1/3"] },
  { n: 24, enun: "Las magnitudes X e Y son directamente proporcionales. Si un valor de X aumenta al doble, ¿qué debe pasar con Y para que la constante de proporcionalidad no cambie?", alt: ["Aumentar al doble", "Disminuir a la mitad", "Mantenerse constante", "Aumentar en 4 unidades"] },
  { n: 25, enun: "Una receta indica agregar 200 g de chocolate por cada 1.000 g de galletas, en proporción. Para una porción de 2.250 g de galletas, ¿cuántos gramos de chocolate se deben agregar?", alt: ["250", "300", "400", "450"] },
  { n: 26, enun: "¿Cuál es el valor de x en la ecuación ax + b = cx + d?", alt: ["(d−b)/(ac)", "(d−b)/(a+c)", "(d−b)/(a−c)", "(b−d)/(ac)"] },
  { n: 27, enun: "¿Cuál es el conjunto solución de la inecuación −3x + 1 < 7?", alt: ["]−2, ∞[", "]−∞, 2[", "]−∞, 8/3[", "]−∞, −8/3["] },
  { n: 28, enun: "¿Cuál de las siguientes ecuaciones NO es equivalente a 5 − 0,01·x = 3/4?", alt: ["5 − x/100 = 0,75", "5 − 1%·x = 75%", "5 − 0,01x = 0,75", "5 − 10⁻¹·x = 75%"] },
  { n: 29, enun: "Patricia y Alberto tienen la misma cantidad de dinero. Patricia compra 4 dulces y le sobran $320; Alberto compra 10 dulces y le sobran $200. ¿Cuál es el precio de un dulce?", alt: ["$10", "$20", "$30", "$40"] },
  { n: 30, enun: "Para un concierto hay A entradas disponibles, cada persona puede comprar hasta 4. Si a Catalina le asignan el turno B, ¿qué desigualdad asegura que alcance a comprar una entrada?", alt: ["B < A/4 − 1", "B < A/4 + 1", "B < 4A − 1", "B < 4A + 1"] },
  { n: 31, enun: "La resta de dos números es 16, donde la cuarta parte del mayor (x) más la mitad del menor (y) es igual al número mayor. ¿Cuál sistema de ecuaciones permite determinar los números?", alt: ["x−y=16 ; 4x+2y=x", "x−y=16 ; x/4+y/2=x", "x−y=16 ; x/8+2y=x", "x−y=16 ; 8x+y/2=x"] },
  { n: 32, enun: "Andrea y Víctor tienen entre los dos 140 estampas; Víctor tiene más y la diferencia entre ambos es de 100. ¿Cuántas estampas tiene Víctor?", alt: ["110", "120", "130", "140"] },
  { n: 33, enun: "Una tabla muestra f(−1)=4, f(0)=5, f(1)=6, f(2)=7, f(3)=8. ¿Cuál expresión algebraica corresponde a esta función?", alt: ["f(x) = x − 5", "f(x) = x + 5", "f(x) = 2x + 5", "f(x) = 2x − 5"] },
  { n: 34, enun: "Considere f(x) = 3x + 4 y g(x) = −1 − 2x, ambas con dominio los reales. Si el punto (a,b) pertenece al gráfico de ambas, ¿cuál es el valor de a?", alt: ["−5", "−1", "3", "7"] },
  { n: 35, enun: "Un gráfico muestra una recta que pasa por (0,−5) y (−1,−7). ¿Cuál función representa ese gráfico?", alt: ["f(x) = −3x + 2", "f(x) = 3x − 2", "f(x) = 2x − 5", "f(x) = −2x + 5"] },
  { n: 36, enun: "Considera f(x) = x² y h(x) = (x+3)² + 4. ¿Qué secuencia de transformaciones genera h(x) a partir de f(x)?", alt: ["Desplazamiento vertical abajo 4 y horizontal derecha 3", "Desplazamiento vertical arriba 4 y horizontal derecha 3", "Desplazamiento vertical abajo 4 y horizontal izquierda 3", "Desplazamiento vertical arriba 4 y horizontal izquierda 3"] },
  { n: 37, enun: "Se patea un balón de fútbol con trayectoria parabólica que alcanza su altura máxima a los 10 segundos. A los 2 segundos alcanzó 40 metros. ¿Cuál función modela la altura después de t segundos?", alt: ["f(t) = −10/9·t² + 200/9·t", "f(t) = 10/9·t² + 200/9·t", "f(t) = −10/9·t² − 200/9·t", "f(t) = 10/9·t² − 200/9·t"] },
];

export const GEOMETRIA = [
  { n: 38, enun: "Se tiene una servilleta en forma de triángulo equilátero, cada lado mide 6 cm. ¿Cuál es la altura, en cm, del triángulo?", alt: ["3√3", "3√5", "6√3", "6√5"] },
  { n: 39, enun: "Constanza cuelga un cuadro que quedó 1/2 m más abajo de lo debido. La escalera mide √7 m y estaba a √3 m de la pared. ¿A qué distancia quedará la escalera de la pared si sube el 1/2 metro que le faltó?", alt: ["1/2 m", "√3/2 m", "1 m", "√3 m"] },
  { n: 40, enun: "En una figura, AC = 20 cm y AO = 1,5 · BP. ¿Cuál es la suma de áreas de los dos semicírculos de centro O y P?", alt: ["26π cm²", "32π cm²", "46π cm²", "52π cm²"] },
  { n: 41, enun: "En tres cuadrados con un cuarto de circunferencia dibujado en cada uno (de A a G), si EF = 2·CD, CD = 2·AB y el perímetro del cuadrado de lado EF es 32 cm, ¿cuál es la longitud de la curva completa?", alt: ["5π cm", "7π cm", "14π cm", "28π cm"] },
  { n: 42, enun: "Para el área de un trapecio con base 8 cm, base 150 mm y altura h (perpendicular al lado AB, mide la mitad de este), Stephanie calcula A = ((8+15)/2)·75 y llega a 862,5 cm². ¿En qué paso está el error?", alt: ["Paso 1 (mezcla unidades: mm y cm)", "Paso 2", "Paso 3", "Paso 4"] },
  { n: 43, enun: "Un contenedor rectangular de base cuadrada tiene altura 64 cm y el lado de la base mide 4 cm. ¿Cuál es su volumen, en cm³?", alt: ["1.012", "1.024", "1.036", "1.048"] },
  { n: 44, enun: "Si el área de un cubo es 54 cm², ¿cuánto mide la diagonal interior del cubo (de un vértice a otro opuesto)?", alt: ["3√2 cm", "3√3 cm", "6√2 cm", "6√3 cm"] },
  { n: 45, enun: "Una alfombra enrollada en forma de cilindro tiene un largo de 8 m. Si el perímetro de la circunferencia de la base es 36π m, ¿cuál es el área lateral externa, en m²?", alt: ["264π", "272π", "288π", "296π"] },
  { n: 46, enun: "Un extractor elimina 1 m³ de oxígeno cada 30 segundos de una habitación de 2 m × 2,5 m × 4 m. ¿En cuánto tiempo se quedará sin oxígeno la habitación?", alt: ["10 minutos", "20 minutos", "40 minutos", "60 minutos"] },
  { n: 47, enun: "Sean los vectores u = (−4, 6) y v = (5, −2). Si u + w = v, ¿cuáles son las coordenadas de w?", alt: ["(−8, 1)", "(0, −7)", "(3, −5)", "(9, −8)"] },
  { n: 48, enun: "Teresa camina desde el paradero (0,0): primero le dicen ir 4 cuadras a la derecha y 7 hacia arriba (broma), luego le corrigen: 3 cuadras a la derecha y 2 hacia abajo. ¿Qué vector describe la traslación total hasta su local de votación?", alt: ["v = (4, 3)", "v = (7, 5)", "v = (4, 9)", "v = (7, 9)"] },
  { n: 49, enun: "Al punto P(3,5) se le aplica una traslación según el vector (a, −b), obteniéndose Q. Luego a Q se le aplica una simetría respecto al eje y. ¿Cuál es la coordenada de la imagen de Q?", alt: ["(3−a, 5−b)", "(3+a, −5+b)", "(3−a, −5−b)", "(−3−a, 5−b)"] },
  { n: 50, enun: "El punto (a, b−2) es simétrico al punto (2, −6) con respecto al eje x. ¿Cuál es el valor de a + b?", alt: ["−10", "−6", "1", "10"] },
  { n: 51, enun: "La recta AB (de A(1,2) a B(4,4)) representa una viga rotada por una grúa 270° respecto al punto A, en sentido antihorario. ¿Cuáles son las nuevas coordenadas del punto B'?", alt: ["(−1, 3)", "(3, −1)", "(−1, 5)", "(5, −1)"] },
];

export const PROBABILIDAD = [
  { n: 52, enun: "Una tabla muestra la cantidad de artículos vendidos en una semana en 48 puntos de venta, con la mayor frecuencia (14 locales) en el intervalo 74–78. ¿Qué se puede afirmar respecto a esta información?", alt: ["La moda de la cantidad de artículos vendidos es 5.", "El artículo se vende más en el norte del país.", "Se venden 78 artículos semanalmente en 14 puntos de venta.", "La cantidad de artículos vendidos que más se repite, lo hace en 14 puntos de venta."] },
  { n: 53, enun: "Una tabla de edades de postulantes (23:1, 32:9, 33:4, 41:1, 52:3) se representará en un gráfico circular. ¿Cuántos grados le corresponden a la edad de 32 años?", alt: ["180°", "90°", "27°", "9°"] },
  { n: 54, enun: "Una tabla de frecuencias acumuladas tiene 6 grupos de datos; se conocen algunas frecuencias absolutas (4, 3, x, y, z, 5) y acumuladas (4, 7, —, —, 35, 40). ¿Cuál es el valor de x + y + z?", alt: ["28", "35", "40", "42"] },
  { n: 55, enun: "Las duraciones (min) de 7 listas de reproducción de Tomás son: 62, 89, 154, 74, 154, 380, 74. ¿Cuál es la media aritmética de la duración de las listas?", alt: ["62", "141", "154", "243"] },
  { n: 56, enun: "Se aplicó una prueba a 3 grupos de 6 estudiantes: grupo 1 (15,17,7,12,15,6), grupo 2 (7,10,12,4,2,7), grupo 3 (10,12,2,7,10,1). ¿Cuál afirmación sobre los promedios es correcta?", alt: ["Todos los grupos tienen distinta media aritmética.", "El grupo 1 y 3 tienen la misma media aritmética.", "El grupo 3 tiene mejor promedio que los restantes.", "El grupo 1 tiene mejor promedio que los restantes."] },
  { n: 57, enun: "Una tabla de edades de postulantes es: 23:1, 32:9, 33:4, 41:9, 52:3. ¿Cuál afirmación respecto a la moda de las edades es correcta?", alt: ["La única moda es 2.", "La única moda es 4.", "La moda no existe.", "Hay más de una moda."] },
  { n: 58, enun: "Un club de baloncesto marcó, en sus últimos 5 partidos, 95, 105, 123, 87 y x puntos. ¿Cuál es el valor de x para que el promedio de puntos por partido sea exactamente 100?", alt: ["80", "85", "90", "95"] },
  { n: 59, enun: "Considera un grupo de 200 datos numéricos. Si C es el tercer cuartil de estos datos, ¿cuál de las siguientes afirmaciones se puede deducir?", alt: ["El percentil 99 de estos datos es mayor que C.", "El percentil 25 es igual a la tercera parte de C.", "En la muestra, hay al menos 50 datos mayores que C.", "En la muestra, hay al menos 50 datos menores o iguales que C."] },
  { n: 60, enun: "Una encuesta sobre la hora de almuerzo entrega: [1,2): 59, [2,3): 63, [3,4): 47, [4,5): 51 personas. ¿En qué horario almuerza el primer 25% de las personas encuestadas?", alt: ["Entre las 1 y las 2 de la tarde.", "Entre las 2 y las 3 de la tarde.", "Entre las 3 y las 4 de la tarde.", "Entre las 4 y las 5 de la tarde."] },
  { n: 61, enun: "Un diagrama de caja y bigotes de asistencia a una feria universitaria muestra cuartiles en 200, 350 y 550 estudiantes. ¿Cuál de las siguientes afirmaciones es verdadera?", alt: ["El percentil 15 es de 200 estudiantes.", "El percentil 25 es de 200 estudiantes.", "El percentil 50 es de 550 estudiantes.", "El percentil 65 es de 550 estudiantes."] },
  { n: 62, enun: "¿Cuál de los siguientes sucesos tiene una probabilidad de ocurrir inferior a 0,5?", alt: ["Que salga sello al lanzar una moneda.", "Obtener un número primo al lanzar un dado de 6 caras.", "Obtener un número mayor a 2 al lanzar un dado de 6 caras.", "Extraer al azar una ficha blanca de una caja con 2 blancas y 6 azules."] },
  { n: 63, enun: "En una prueba de 10 preguntas, las primeras 4 tienen 5 alternativas y el resto son de verdadero y falso. Contestando todo al azar, ¿cuál es la probabilidad de acertar todas?", alt: ["1/4 · 1/6", "(1/4 · 1/6)¹⁰", "1/2 · 1/5", "(1/5)⁴ · (1/2)⁶"] },
  { n: 64, enun: "En una caja hay 7 bolitas numeradas del 1 al 7. Si se saca una al azar, ¿cuál es la probabilidad de que su número sea par o mayor que 5?", alt: ["1/7", "2/7", "4/7", "5/7"] },
  { n: 65, enun: "Paulina y Guillermo tienen 10 bolitas cada uno, numeradas del 1 al 10 (verdes y blancas respectivamente). Guillermo le da una al azar a Paulina, luego Paulina le da una al azar a Guillermo. ¿Cuál es la probabilidad de que se haya intercambiado el mismo número?", alt: ["1/10", "2/10", "1/11", "2/11"] },
];
